import Navbar from "@/componenets/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  params, children,
}: Readonly<{
  params: { lang: string; };
  children: React.ReactNode;
}>) {
  const locale = params.lang as 'en';
  return (
    <html lang="en">
      <body>
        <p>From layout: {params.lang}</p>
        <Navbar locale={locale}/>
        {children}
      </body>
    </html>
  );
}
